package com.aksiyoncuk.notification.entity;

public enum NotificationType {
  USER_FOLLOWED,
  POST_LIKED,
  POST_COMMENTED,
  JOB_APPLICATION_RECEIVED,
  JOB_APPLICATION_ACCEPTED,
  JOB_APPLICATION_REJECTED,
  FREELANCE_ORDER_CREATED,
  FREELANCE_ORDER_STARTED,
  FREELANCE_ORDER_REJECTED,
  FREELANCE_ORDER_DELIVERED,
  FREELANCE_REVISION_REQUESTED,
  FREELANCE_REVISION_ACKNOWLEDGED,
  FREELANCE_ORDER_COMPLETED,
  FREELANCE_CANCELLATION_REQUESTED,
  FREELANCE_CANCELLATION_ACCEPTED,
  FREELANCE_CANCELLATION_REJECTED,
  FREELANCE_REVIEW_RECEIVED
}
